
package org.usfirst.frc4919.frc2019NEW.subsystems;

import org.usfirst.frc4919.frc2019NEW.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 *//*
     * public class Pneumatics extends Subsystem {
     * 
     * // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
     * 
     * // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
     * 
     * // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS private
     * DoubleSolenoid frontPistons; private DoubleSolenoid backPistons; private
     * DoubleSolenoid towerPiston; private DoubleSolenoid keyPiston; private
     * Compressor compressor; private DoubleSolenoid gearShifter;
     * 
     * // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
     * 
     * public Pneumatics() { // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER
     * ID=CONSTRUCTORS frontPistons = new DoubleSolenoid(0, 0, 1);
     * addChild("Front Pistons",frontPistons);
     * 
     * 
     * backPistons = new DoubleSolenoid(0, 2, 3);
     * addChild("Back Pistons",backPistons);
     * 
     * 
     * towerPiston = new DoubleSolenoid(0, 4, 5);
     * addChild("Tower Piston",towerPiston);
     * 
     * 
     * keyPiston = new DoubleSolenoid(0, 6, 7); addChild("Key Piston",keyPiston);
     * 
     * 
     * compressor = new Compressor(0); addChild("Compressor",compressor);
     * 
     * 
     * gearShifter = new DoubleSolenoid(1, 0, 1);
     * addChild("Gear Shifter",gearShifter);
     * 
     * 
     * 
     * // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS }
     * 
     * @Override public void initDefaultCommand() { // BEGIN AUTOGENERATED CODE,
     * SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
     * 
     * 
     * // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
     * 
     * // Set the default command for a subsystem here. // setDefaultCommand(new
     * MySpecialCommand()); }
     * 
     * @Override public void periodic() { // Put code here to be run every loop
     * 
     * }
     * 
     * // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
     * 
     * 
     * // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
     * 
     * // Put methods for controlling this subsystem // here. Call these from
     * Commands.
     * 
     * }
     * 
     */