
package org.usfirst.frc4919.frc2019NEW.subsystems;

import org.usfirst.frc4919.frc2019NEW.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Pneumatics extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid frontPistons;
    public static DoubleSolenoid backPistons;
    public static DoubleSolenoid towerPiston;
    public static DoubleSolenoid keyPiston;
    public static Compressor compressor;
    public static DoubleSolenoid gearShifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Pneumatics() { // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS}
        frontPistons = new DoubleSolenoid(0, 0, 1);
        addChild("Front Pistons", frontPistons);

        backPistons = new DoubleSolenoid(0, 2, 3);
        addChild("Back Pistons", backPistons);

        towerPiston = new DoubleSolenoid(0, 6, 7);
        addChild("Tower Piston", towerPiston);

        keyPiston = new DoubleSolenoid(0, 4, 5);
        addChild("Key Piston", keyPiston);

        gearShifter = new DoubleSolenoid(1, 2, 3);
        addChild("Gear Shifter", gearShifter);

        compressor = new Compressor(0);
        addChild("Compressor", compressor);

    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS }

    @Override
    public void initDefaultCommand() { // BEGIN AUTOGENERAOTBUILDER ID=DEFAULT_CTTED COACODE, SROBOTBUI

        // EN, SOURCE=ROBED LDER ID=DEFAULT_COMMANDDEOMMANDD AUTOGENEROURCE=
        // Insert nuclear codes here

        // Set the default command for a subsystem here. // setDefaultCommand(new
        // MySpecialCommand());
    }

    @Override
    public void periodic() { // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem // here. Call these from Commands.
    public void extendF() {
        frontPistons.set(DoubleSolenoid.Value.kForward);
    }

    public void retractF() {
        frontPistons.set(DoubleSolenoid.Value.kReverse);
    }

    public void extendB() {
        backPistons.set(DoubleSolenoid.Value.kForward);
    }

    public void retractB() {
        backPistons.set(DoubleSolenoid.Value.kReverse);
    }

    public void extendT() {
        towerPiston.set(DoubleSolenoid.Value.kForward);
    }

    public void retractT() {
        towerPiston.set(DoubleSolenoid.Value.kReverse);
    }

    public void extendK() {
        keyPiston.set(DoubleSolenoid.Value.kForward);
    }

    public void retractK() {
        keyPiston.set(DoubleSolenoid.Value.kReverse);
    }

    public void extendG() {
        keyPiston.set(DoubleSolenoid.Value.kForward);
    }

    public void retractG() {
        keyPiston.set(DoubleSolenoid.Value.kReverse);
    }
}